llm:
  provider:
    provider: anthropic  # Options: openai, anthropic, openrouter, ollama
    model: claude-sonnet-4-5-20250929   # See providers.py DEFAULT_MODELS for available options
    temperature: 0.1
    max_tokens: 8192    # Required for Anthropic models
    api_key: null  # Set via ANTHROPIC_API_KEY environment variable
    api_base: null   # Optional, for custom endpoints
    extra_kwargs: {} # Additional provider-specific settings

    # Retry and rate limiting settings (NEW)
    max_retries: 3   # Number of retries on failure
    retry_delay: 1.0  # Initial delay between retries (seconds)
    retry_exponential_backoff: true  # Use exponential backoff for retries
    max_retry_delay: 60.0  # Maximum delay between retries (seconds)
    rate_limit_requests_per_minute: null  # Optional: Limit API requests per minute
    rate_limit_tokens_per_minute: null    # Optional: Limit tokens per minute

    # Cost tracking settings (NEW)
    enable_cost_tracking: true  # Track API costs and token usage
    cost_metrics_path: .cache/llm/cost_metrics.json  # Path to save cost metrics

  cache_dir: .cache/llm
  cache_max_entries: 10000  # Maximum cache entries before auto-cleanup (NEW)
  cache_cleanup_interval: 100  # Trigger cleanup every N cache puts (NEW)
  max_workers: 4
  batch_size: 10

semgrep:
  default_rules:
    - auto
  max_target_files: 1000
  timeout: 300
  jobs: null

analysis:
  max_file_size: 1000000
  max_related_files: 10
  analyze_imports: true
  analyze_references: true
  excluded_dirs:
    - venv
    - node_modules
    - .git
    - __pycache__
    - build
    - dist
    - migrations
  excluded_files:
    - "*.pyc"
    - "*.pyo"
    - "*.pyd"
    - "*.so"
    - "*.dylib"
    - "*.min.js"
    - "*.min.css"
    - "*.map"
  languages:
    - python
    - javascript
    - typescript
    - java
    - ruby
    - php
    - go
    - csharp
  max_analysis_time: 30
  cache_analysis: true

rag:
  persist_dir: .semgrepai/db
  collection_name: findings
  distance_metric: cosine
  embeddings_model: all-MiniLM-L6-v2

report:
  output_dir: reports
  formats:
    - html
    - json
    - sarif
  max_findings_per_page: 50
